### ISSUE TITLE
Unable to open Pattypan 22.03 (and .02) with M2 Mac

### ISSUE THREAD

**Issue by trnstlntk** [yarl/pattypan#172]
I'm unable to open Pattypan 22.03 on my M2 Mac. Specs are:
* MacBook Air M2, 2022
* MacOS 13.1

When attempting to open pattypan.jar by double-clicking, I get:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/9881645/222375966-52e9dff9-bea1-4b1c-b219-cb8532d01ae8.png">

When attempting to open in the Terminal by entering `java -jar pattypan\ 22.03.jar` I get:

```
Mar 02, 2023 9:31:59 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @22de69b2'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/fokky/.openjfx/cache/17.0.2-ea/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/fokky/.openjfx/cache/17.0.2-ea/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:383)
	at java.base/java.lang.Class.forName(Class.java:376)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/fokky/.openjfx/cache/17.0.2-ea/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/fokky/.openjfx/cache/17.0.2-ea/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:383)
	at java.base/java.lang.Class.forName(Class.java:376)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.application.Platform.startup(Platform.java:113)
	at pattypan.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.application.Platform.startup(Platform.java:113)
	at pattypan.Launcher.main(Unknown Source)
```

**Comment by trnstlntk** [comment]
I get exactly the same behavior when trying to open Pattypan 22.02.

**Comment by PythonCoderAS** [comment]
Same behavior with M1. Some digging shows that https://github.com/openjfx/javafx-maven-plugin/issues/112 and https://gluonhq.com/javafx-for-apple-m1/

**Comment by PythonCoderAS** [comment]
I just built a version for M1/M2. Built it yourself:

```bash
brew install ant # If you don't have ant
cd /tmp/
git clone https://github.com/yarl/pattypan.git
cd pattypan
wget https://download2.gluonhq.com/openjfx/20/openjfx-20_osx-aarch64_bin-sdk.zip
ant
```

**Comment by psubhashish** [comment]
[22.02](https://github.com/yarl/pattypan/issues/158#issuecomment-1450197511) worked actually with an initial [hiccup](https://github.com/yarl/pattypan/issues/158#issuecomment-1450094881), not related to Pattypan.

**Comment by anishsheela** [comment]
I am still not able to install it.

```
anish@ip-192-xxx pattypan % java -jar pattypan.jar
Error: LinkageError occurred while loading main class pattypan.Launcher
	java.lang.UnsupportedClassVersionError: pattypan/Launcher has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

**Comment by mikima** [comment]
Same error on Mac Intel.

Cloned and compiled it as suggested by @PythonCoderAS but the resulting jar fails when launched.
<img width="372" alt="Screenshot 2023-10-05 at 22 55 45" src="https://github.com/yarl/pattypan/assets/907536/732af521-e161-49e8-8ce8-f64a0fdea3b5">

**Comment by PythonCoderAS** [comment]
> Same error on Mac Intel.
> 
> Cloned and compiled it as suggested by @PythonCoderAS but the resulting jar fails when launched. <img alt="Screenshot 2023-10-05 at 22 55 45" width="372" src="https://user-images.githubusercontent.com/907536/273047513-732af521-e161-49e8-8ce8-f64a0fdea3b5.png">

The instructions are only for M1/M2 macs. For intel, use this URL: `https://download2.gluonhq.com/openjfx/20/openjfx-20_osx-x64_bin-sdk.zip`

**Comment by VDK** [comment]
Installing the [https://www.oracle.com/java/technologies/downloads/#jdk21-windows JDK developer kit] fixed a similar error for me on a Windows machine

**Comment by cloventt** [comment]
The issue is that the builder is not able to cope with multiple versions of the same OpenJFX distribution. If you download both the x64 and aarch64 versions of the MacOS OpenJFX for Java lib, they both get unzipped into the `bin/` folder, and they clobber each other. This results in an executable that cannot run.

I've compiled a version including *only* the OpenJFX bindings for MacOS on Apple Silicon, and it works fine. It would be good to include the arm64-specific JAR in the releases for users on that platform.

**Comment by Abbe98** [comment]
Pattypan now support all Macs with Apple processors: https://github.com/yarl/pattypan/releases/tag/v26.02
