### ISSUE TITLE
Cannot launch with OpenJDK 1.7.0_101

### ISSUE THREAD

**Issue by nemobis** [yarl/pattypan#9]
Launching the jar fails completely in Ubuntu 15.10:
```
guest-fJvug7@faggio:~/Scaricati$ java -jar pattypan.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: pattypan/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
guest-fJvug7@faggio:~/Scaricati$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by yarl** [comment]
It's probably because code is written in Java 8. Can you update OpenJDK to version 8 and take a look again?

**Comment by nemobis** [comment]
Paweł Marynowski, 28/07/2016 09:10:
> It's probably because code is written in Java 8. Can you update OpenJDK
> to version 8 and take a look again?

I'll try when I reach these Ubuntu machines again (they are not mine; in 
Fedora I had no problems). Is the easiest method to update to Ubuntu 
16.04? http://packages.ubuntu.com/xenial/openjdk-8-jre

**Comment by yarl** [comment]
Yes, ```openjdk-8-jre``` should be the correct package. I'm closing this issue, since the problem was old Java version.

**Comment by intracer** [comment]
you don't need too update ubuntu
 http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by nemobis** [comment]
Ilya, 14/08/2016 17:12:
> you don't need too update ubuntu
> http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

It's not my machine, so I prefer a more stable solution.

**Comment by intracer** [comment]
It is stable, it just installs Oracle JDK, which is certified for Ubuntu http://www.oracle.com/technetwork/java/javase/certconfig-2095354.html
